\copy creditos(
    nombre_acreditado,
    numero_socio_cliente,
    numero_credito,
    sucursal,
    clasificacion_credito,
    producto_credito,
    tipo_cuota,
    fecha_otorgamiento,
    monto_original,
    fecha_vencimiento,
    tasa_ord_nom_anual,
    tasa_moratoria_nom_anual,
    plazo_credito,
    frecuencia_pago_capital,
    frecuencia_pago_intereses,
    dias_mora_cartera,
    capital_vigente,
    capital_vencido,
    intereses_moratorios_devengados_no_cobrados,
    intereses_ordinarios_devengados_no_cobrados_vigente,
    intereses_devengados_no_cobrados_vencido,
    intereses_devengados_no_cobrados_cuentas_orden,
    fecha_ultimo_pago_capital,
    monto_ultimo_pago_capital,
    fecha_ultimo_pago_interes,
    monto_ultimo_pago_interes,
    renovado_reestructurado_normal,
    emproblemado,
    vigente_vencido,
    cargo_parte_relacionada,
    monto_garantia_liquida,
    cuentas_garantia_liquida,
    monto_garantia_prendaria,
    monto_garantia_hipotecaria,
    eprc_para_parte_cubierta,
    eprc_para_parte_expuesta,
    eprc_intereses_cave,
    anio,
    mes) from 'Cartera.csv' delimiter ',' csv header;

psql -U emelchor -d quantiva -h localhost

\copy captacion(numero_socio,
    nombre_socio,
    num_contrato_cuenta,
    sucursal,
    fecha_apertura_contratacion,
    tipo_deposito_cuenta_producto,
    fecha_retiro_ultimo,
    fecha_deposito_ultimo,
    fecha_vencimiento,
    plazo_deposito_dias,
    forma_pago_rendimientos_dias,
    tasa_interes_nominal_pactada_anual,
    saldo_promedio,
    monto_ahorro_deposito_plazo_capital,
    intereses_devengados_no_pagados_cierre_mes,
    saldo_total_cierre_mes,
    intereses_generados_mes,
    promotor,
    no_socio_padre_tutor,
    anio,
    mes) from 'Captacion.csv' delimiter ',' csv header;

\copy socios(sucursal,
    numero_socio,
    nombre_completo,
    sexo,
    fecha_nacimiento,
    curp,
    ife,
    estado_civil,
    fecha_ingreso,
    fecha_baja,
    capital_social,
    anio,
    mes) from 'Socios.csv' delimiter ',' csv header;